parameters:
  # Pagination
  skip:
    name: skip
    description: Number of pages for skipping.
    in: query
    required: true
    type: integer

  take:
    name: take
    description: Number of items in single page.
    in: query
    required: true
    type: integer

  # Users
  idNumberQuery:
    name: id_number
    description: The Isreali identification number of a user.
    in: query
    required: false
    type: integer

  userId:
    name: user_id
    description: The internal identification number of a user.
    in: path
    required: true
    type: integer

  userIdQuery:
    name: user_id
    description: The internal identification number of a user.
    in: query
    required: true
    type: integer

  userIdQueryNoReq:
    name: user_id
    description: The internal identification number of a user.
    in: query
    required: false
    type: integer

  roleId:
    name: role_id
    description: The internal identification number of a role.
    in: query
    required: true
    type: integer

  coachId:
    name: coach_id
    description: The internal identification number of a coach.
    in: path
    required: true
    type: integer

  # Team
  teamIdQuery:
    name: team_id
    description: The internal identification number of a team.
    in: query
    required: true
    type: integer

  teamIdPath:
    name: team_id
    description: The internal identification number of a team.
    in: path
    required: true
    type: integer

  # Announcements
  announcementId:
    name: announcement_id
    description: The internal identification number of an announcement.
    in: path
    required: true
    type: integer

  # Videos
  videoCategory:
    name: category
    description: Video category.
    in: query
    required: false
    type: string

  videoSubCategory:
    name: sub_category
    description: Video sub-category.
    in: query
    required: false
    type: string

  videoId:
    name: video_id
    description: The internal identification number of video.
    in: path
    required: true
    type: integer

  exerciseId:
    name: exercise_id
    description: The internal identification number of an excercise.
    in: path
    required: true
    type: integer

  exerciseIdQuery:
    name: exercise_id
    description: The internal identification number of an excercise.
    in: query
    required: true
    type: integer

  trainingId:
    name: training_id
    description: The internal identification number of an training/test.
    in: path
    required: true
    type: integer

  trainingIdQuery:
    name: training_id
    description: The internal identification number of an training/test.
    in: query
    required: true
    type: integer

  # Score
  scoreId:
    name: ex_score_id
    description: The internal identification number of an score.
    in: path
    required: true
    type: integer

  scoreTypeQuery:
    name: score_type
    description: "Can be one of the following: time_duration, weight, sets, reps."
    in: query
    required: true
    type: string

  isTestScoreQuery:
    name: is_test
    description: indicates wether the recorded score is test score or train score.
    in: query
    required: false
    type: string
