exports.seed = (knex, Promise) => {
  return knex("exercises_scores")
    .del()
    .then(() => {
      return knex("exercises_scores").insert([
        {
          user_id: 5,
          training_id: 1,
          exercise_id: 1,
          time_duration: 0,
          sets: 2,
          reps: 100,
          weight: 5,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 5,
          training_id: 1,
          exercise_id: 3,
          time_duration: 100,
          sets: 2,
          reps: 4,
          weight: 0,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 5,
          training_id: 1,
          exercise_id: 5,
          time_duration: 0,
          sets: 3,
          reps: 50,
          weight: 3,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 6,
          training_id: 2,
          exercise_id: 2,
          time_duration: 0,
          sets: 2,
          reps: 100,
          weight: 5,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 6,
          training_id: 2,
          exercise_id: 3,
          time_duration: 100,
          sets: 2,
          reps: 4,
          weight: 0,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 6,
          training_id: 2,
          exercise_id: 5,
          time_duration: 0,
          sets: 3,
          reps: 50,
          weight: 3,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 7,
          training_id: 3,
          exercise_id: 3,
          time_duration: 0,
          sets: 2,
          reps: 100,
          weight: 5,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 7,
          training_id: 3,
          exercise_id: 4,
          time_duration: 100,
          sets: 2,
          reps: 4,
          weight: 0,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          user_id: 7,
          training_id: 3,
          exercise_id: 5,
          time_duration: 0,
          sets: 3,
          reps: 50,
          weight: 3,
          is_test: false,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
      ]);
    });
};
