const bcrypt = require("bcrypt");

exports.seed = (knex, Promise) => {
  return knex("users")
    .del()
    .then(() => {
      return knex("users").insert([
        {
          username: "admin-user",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "אדמין",
          last_name: "אדמין",
          email: "admin@test.com",
          id_number: "316371231",
          role_id: 1,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "coach-user-a",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "דניאל",
          last_name: "דיין",
          email: "coacha@test.com",
          id_number: "123456789",
          role_id: 2,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "coach-user-b",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "ניר",
          last_name: "בגיזדה",
          email: "coachb@test.com",
          id_number: "223456789",
          role_id: 2,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "coach-user-c",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "רועי",
          last_name: "הנדלר",
          email: "coachc@test.com",
          id_number: "323456789",
          role_id: 2,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "trainee-user-a",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "גל",
          last_name: "כהן",
          email: "traineea@test.com",
          id_number: "423456789",
          role_id: 3,
          age: 15,
          city: "Tel-Aviv",
          zipcode: 123456,
          address: "test address",
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "trainee-user-b",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "אילן",
          last_name: "בר",
          email: "traineeb@test.com",
          id_number: "523456789",
          role_id: 3,
          age: 17,
          city: "Petah-Tikva",
          zipcode: 123456,
          address: "test address",
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "trainee-user-c1",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "אריאל",
          last_name: "רוט",
          email: "traineec1@test.com",
          id_number: "623456789",
          role_id: 3,
          age: 20,
          city: "Ashkelon",
          zipcode: 123456,
          address: "test address",
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "trainee-user-c2",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "אסי",
          last_name: "ברק",
          email: "traineec2@test.com",
          id_number: "723456789",
          role_id: 3,
          age: 20,
          city: "Ashkelon",
          zipcode: 123456,
          address: "test address",
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
        {
          username: "guest",
          password: bcrypt.hashSync("1", bcrypt.genSaltSync()),
          first_name: "אורח",
          last_name: "לרגע",
          email: "not-assigned@test.com",
          id_number: "823456789",
          role_id: 4,
          created_at: knex.fn.now(),
          updated_at: knex.fn.now(),
        },
      ]);
    });
};
